# Generated by Django 6.0.7 on 2026-07-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('ubicacion_gps', models.CharField(help_text='Coordenadas GPS o Dirección de estancia/vivienda', max_length=255, verbose_name='Ubicación de Estancia / Vivienda')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('lugar_estudios', models.CharField(max_length=200, verbose_name='Universidad / Centro de Estudios')),
                ('grado_especialidad', models.CharField(help_text='Ejemplo: Cirugía Bovina, Nutrición Animal, Reproducción', max_length=150, verbose_name='Grado de Especialidad')),
                ('experiencia_laboral', models.TextField(blank=True, help_text='Resumen o años de experiencia en campo', null=True, verbose_name='Experiencia Laboral')),
                ('nivel_academico', models.CharField(choices=[('BASICO', 'Nivel Básico'), ('INTERMEDIO', 'Nivel Intermedio'), ('ALTO', 'Nivel Alto'), ('ESPECIALIZADO', 'Especializado'), ('EXPERTO', 'Veterinario Experto')], default='BASICO', max_length=20, verbose_name='Nivel Académico / Experiencia')),
            ],
            options={
                'verbose_name': 'Especialista Veterinario',
                'verbose_name_plural': 'Especialistas Veterinarios',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('ubicacion_gps', models.CharField(help_text='Coordenadas GPS o Dirección de estancia/vivienda', max_length=255, verbose_name='Ubicación de Estancia / Vivienda')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombre_finca', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de la Finca/Estancia')),
            ],
            options={
                'verbose_name': 'Usuario Ganadero',
                'verbose_name_plural': 'Usuarios Ganaderos',
            },
        ),
    ]
