# Generated by Django 6.0.7 on 2026-08-19 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CosechaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('CITRICO', 'Cítricos (Naranja, Limón, Mandarina)'), ('FRUTA', 'Otras Frutas Frescas')], default='CITRICO', max_length=20)),
                ('precio_justo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(default='Cien', max_length=50)),
                ('cantidad_disponible', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cosechas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_cosechas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('VENDEDOR', 'Productor / Vendedor'), ('COMPRADOR', 'Comprador / Supermercado')], default='COMPRADOR', max_length=20)),
                ('correo', models.EmailField(blank=True, help_text='Correo electrónico de contacto', max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('OTRO', 'Otro / Prefiero no decir')], default='M', max_length=10)),
                ('cedula', models.CharField(blank=True, help_text='Cédula o identificación oficial', max_length=30, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('finca', models.CharField(blank=True, help_text='Nombre de la finca o negocio', max_length=150, null=True)),
                ('direccion_exacta', models.TextField(blank=True, help_text='Comunidad, comarca o dirección', null=True)),
                ('region', models.CharField(default='Nueva Guinea', max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
