# Generated by Django 6.0.7 on 2026-07-29 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CosechaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(help_text='Ej. Naranja agria, Limón criollo, Mandarina, Banano', max_length=100)),
                ('categoria', models.CharField(choices=[('FRUTA', 'Frutas en General'), ('CITRICO', 'Cítricos')], default='FRUTA', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Detalles del estado de la cosecha')),
                ('precio_justo', models.DecimalField(decimal_places=2, help_text='Precio sugerido sin intermediarios', max_digits=10)),
                ('unidad_medida', models.CharField(help_text='Ej. Saco, Docena, Cien, Unidad', max_length=50)),
                ('cantidad_disponible', models.PositiveIntegerField(help_text='Inventario digital en tiempo real')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('disponibilidad_tierra', models.BooleanField(default=True, help_text='Indica si la tierra tiene producción activa actualmente')),
                ('productor', models.ForeignKey(limit_choices_to={'perfil__rol': 'USUARIO'}, on_delete=django.db.models.deletion.CASCADE, related_name='cosechas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador del Sistema'), ('USUARIO', 'Usuario (Productor o Comprador)'), ('AUDITOR', 'Auditor de Calidad y Precios Justos')], default='USUARIO', max_length=15)),
                ('region', models.CharField(help_text='Municipio o Departamento (ej. Nueva Guinea)', max_length=100)),
                ('comunidad_o_direccion', models.CharField(help_text='Dirección del negocio o finca', max_length=200)),
                ('coordenadas_gps', models.CharField(blank=True, help_text='Ubicación GPS opcional', max_length=100, null=True)),
                ('nombre_finca_o_negocio', models.CharField(blank=True, max_length=150, null=True)),
                ('historia_productor', models.TextField(blank=True, help_text='Breve descripción de su identidad local', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
