# Generated by Django 6.0.7 on 2026-08-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0002_cosechaproducto_es_preventa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='banco_nombre',
            field=models.CharField(blank=True, default='Banco LAFISE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='titular_cuenta',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tickettransaccion',
            name='referencia_pago',
            field=models.CharField(blank=True, default='Efectivo contra entrega', max_length=100, null=True),
        ),
    ]
